### PR TITLE
Fix cross platform and non default prefix

### LINKED ISSUE #4: Can't require "npm install -g" installed packages on windows
I tried out requireg today, but I saw that it doesn't seem to check %appdata%\npm\node_modules on windows, which seems to be where modules are globally installed to by default.

### PR DESCRIPTION
**Pull request by mhofman**
- Make tests run on Windows
- Check both prefix and node execution path (allows to resolve packages like npm that are globally installed even when the user has overridden the default prefix). See https://github.com/mjeanroy/bower-npm-resolver/issues/15
- Change default prefix location on Windows to %APPDATA%\npm. Fixes #4

### CODE REVIEW

File: test/requiregSpec.js [hunk 1]
```diff
@@ -52,15 +54,15 @@ describe('requireg', function () {
 
       it('should have the expected module path', function () {
         expect(requiregModule.resolve('beaker'))
-          .to.be.equal(__dirname + '/fixtures/lib/node_modules/beaker/index.js')
-      }) 
+          .to.be.equal(path.join(__dirname, 'fixtures', 'lib', 'node_modules', 'beaker', 'index.js'))
```
Comment (jakub-g) [inline test/requiregSpec.js:57]: Hi @mhofman,
Just FYI, as far as I remember you can put `fixtures/lib/node_modules/beaker/index.js` here and `path.join` will take care to normalize it (passing multiple params is not a crime though, matter of personal taste)

https://nodejs.org/api/path.html#path_path_join_path

> The path.join() method join all given path segments together using the platform specific separator as a delimiter, then normalizes the resulting path.

Other than that LGTM :+1:

**Comment by h2non** [comment]
Thanks! Will release a new version tomorrow in `npm`!

File: test/requiregSpec.js (hunk 1 above)
Comment (mhofman) [reply test/requiregSpec.js:57]: Yeah I know, but I prefer not to rely on `path.join` normalizing things. Since it normalizes after joining, you temporarily have a path that has potentially both separators and I'm always worried something might get mixed up. I agree it's more a matter of personal taste.

In this case, there was no `path.join` before, and I actually leverage the individual parameters in other tests by passing different values depending on the platform, so it's also more consistent to have it everywhere.

**Comment by h2non** [comment]
`requireg@0.1.6`is now available in `npm`.
